Allow roles to add manga
jckli/mangaupdates-bot pull request #36
Opened 2022-09-18 10:42 UTC by ethan-sonza

2022-09-18 22:31 UTC, jckli requested changes
Other than these changes, it LGTM! I may also change some of the variables just for organization sake as well as test it a bit after these changes, but thanks for the PR!

2022-09-18 22:31 UTC, jckli commented on cogs/manga_main.py
> +        permissionError = discord.Embed(title="Error", color=0xff4f4f, description=("You don't have permission to add manga. Allow roles to add manga with `/server add_role`."))
I would rather you move this to line 297, just for organization sake as it isn't used anywhere else I believe.

2022-09-18 22:31 UTC, jckli commented on README.md
> +**Mongo DB**
```suggestion

**Mongo DB**
```

2022-09-18 22:31 UTC, jckli commented on README.md
> +**[MangaUpdates](https://www.mangaupdates.com/)**
```suggestion

**[MangaUpdates](https://www.mangaupdates.com/)**
```

2022-09-18 22:31 UTC, jckli commented on README.md
> +- `TOKEN`: Discord bot private key
```suggestion
- `TOKEN`: Discord Bot Token
```

2022-09-19 00:12 UTC, ethan-sonza commented on core/mongodb.py
> +        host = os.environ.get("MONGO_HOST")
No problem, will revert these. Was mainly a convenience for me to setup a local mongodb host.

2022-09-19 00:13 UTC, ethan-sonza commented on cogs/manga_main.py
> +                    if self.bot.user and self.bot.user.avatar:
My bot has no avatar/icon, so I was getting the error: `'None' has no '.url'`

2022-09-19 00:14 UTC, ethan-sonza commented on cogs/manga_general.py
> +    @server.command(name="add_role", description="Add roles that are allowed to add to the manga list")
What if we make a separate prefix for this? eg. `/role add @ROLE`

2022-09-19 00:23 UTC, jckli commented on cogs/manga_main.py
> +                    if self.bot.user and self.bot.user.avatar:
Ah interesting, yeah I didn't think about that. Makes sense.

2022-09-24 01:29 UTC, jckli commented
Hmm, testing this, the manga remove command is not changed and still checks for administrator permission. Other than that everything seems working and fine. I will merge this into a branch on the original mangaupdates-bot repository and change some variable names and fix that.

Sorry about not being very active these past couple days. Had a bunch of work to do. :/

2022-09-24 01:31 UTC, merged